### PR TITLE
Remove alert-library.js

### PR DESCRIPTION
**Pull request by mfcrocker**
# What and why?
We suspected that alert-library.js wasn't being used due to Design System alerting and that seems to be the case. This PR removes it.

# How to test?
Smoke test, especially around error handling

# Jira

### CODE REVIEW

**Review by matthew-robinson-ons — COMMENTED** [review]
Tested locally and all looks good, the flash session fix needs to be merged to fully test  as currently getting the internal server error when deployed through spinnaker.

**Review by SteveScorfield — APPROVED** [review]
Tested locally and works as expected. Once the fix has been merged with this, it will work fine in GCP. Approved

**Review by matthew-robinson-ons — APPROVED** [review]
tested locally and through spinnaker. All looks as expected

**Pull request merged**
