### PR TITLE
Multimode create survey

### PR DESCRIPTION
**Pull request by matthew-robinson-ons**
# What and why?

For the rollout of multimode the create survey and edit survey pages need to updated to include the new multimode option for a survey. There is also a number of usability improvements included in both of those pages. 
# How to test?
Deploy the survey service changes to your environment and test the create and edit survey pages to ensure functionality and usability is as expected. 
# Trello
https://trello.com/c/2IZvLNGn/2450-multimode-mvp-creating-and-editing-existing-survey-to-add-multimode

### CODE REVIEW

**Comment by matthew-robinson-ons** [comment]
[Multimode MvP - Creating and editing existing survey to add multimode](https://trello.com/c/2IZvLNGn/2450-multimode-mvp-creating-and-editing-existing-survey-to-add-multimode)

**Review by anwilkie — APPROVED** [review]
Tested both this and the survey PR out and they seem okay (I can create and edit surveys and their modes). I ran the acceptance tests with `make helm` and they failed twice in a row due to timeout, but on the third time they passed, so I guess it was an intermittent failure.

**Pull request merged**
