### PR TITLE
Iteration changes for rops to view and reply on non survey messages

### PR DESCRIPTION
**Pull request by creativeappdevamit**
# What and why?

# How to test?

# Trello
https://trello.com/c/3sJKB2KU/779-user-account-creation-something-else-rops-iteration

### CODE REVIEW

**Comment by warrenbailey** [comment]
It appears to be missing the email on the message when you view it. Apart from that the functionality looks good

**Comment by warrenbailey** [comment]
looks like the respondent is wrong too, it's shows ONS.

**Comment by warrenbailey** [comment]
fixed the first issue, the second one is general issue with secure message so raised a bug for it

**Review by insacuri — APPROVED** [review]

**Pull request merged**
