### PR TITLE
RAS 967: Upgrade ROps to Flask 3

### PR DESCRIPTION
**Pull request by SteveScorfield**
# What and why?
We need to remove vulnerabilities and deprecations from our code base. This PR updates Werkzeug and Flask-paginate. This PR also removes the deprecation resulting from Flask Markup.

# How to test?
Run unit tests and test in your dev env.

# Jira
https://jira.ons.gov.uk/browse/RAS-926
https://jira.ons.gov.uk/browse/RAS-967

### CODE REVIEW

**Review by LJBabbage — CHANGES_REQUESTED** [review]
I get strange pagination with 11 items
image

**Review by anwilkie — APPROVED** [review]
The pagination issue Lewis highlighted has been fixed, and I couldn't see any other issues.

**Review by LJBabbage — APPROVED** [review]

**Pull request merged**
