### PR TITLE
Design system 32.2.4

### PR DESCRIPTION
**Pull request by boxadesign**
# What and why?

Upgraded r'ops to use the latest version of the design system (32.2.4) https://github.com/ONSdigital/design-system/releases

# How to test?

- Ensure ui is as expected.
- Tests pass.

# Trello
https://trello.com/c/TXtwOaeO

### CODE REVIEW

**Comment by warrenbailey** [comment]
For some reason this seems to stop the collection exercise going to a "READY FOR LIVE" state and it just stays in "SCHEDULED"

**Review by creativeappdevamit — APPROVED** [review]

**Pull request merged**
